
import {
  Code, Smartphone, Brain, Search, Cloud, ShieldCheck, type LucideIcon,
  Target, Lightbulb, Settings, Server, Database, Users, Briefcase, Award,
  TrendingUp, Palette, FileText, LayoutGrid, PenTool, Globe, Zap, CheckSquare,
  DollarSign, Edit, ExternalLink, Eye, EyeOff, FileQuestion, Github, Link as LinkIconLucide,
  HelpCircle, MessageSquare, MessageCircleQuestion, BarChart3, Home, Info,
  UserCircle, User as UserIconLucide, Mail, PanelLeft, LogOut, PlusCircle,
  Trash2, MoreHorizontal, Save, ArrowLeft, ArrowRight, ArrowUp, Menu, X,
  Code2 as CodeXml, FolderGit2, AlignCenter, BadgeAlert, MessageSquareText,
  Star, Send, CalendarDays, Layers, Tag, Phone, MapPin, Bot, ChevronDown, Activity, ShoppingCart,
  Cpu, GitBranch, HardDrive, Keyboard, Laptop, Network, Terminal, Webhook, Wifi, Component, Package, Braces,
  GitCommit, GitMerge, GitPullRequest, Tablet, Puzzle, AppWindow, Quote, Building // Added Building icon
} from 'lucide-react';

// Note: Some icons like Linkedin, Twitter, Loader2, MapPin, Phone, Tag are mapped to existing Lucide icons
// as placeholders because exact brand/utility icons might not be available in lucide-react.
// For precise branding, consider using inline SVGs or a dedicated brand icon library.

export const iconMap: Record<string, LucideIcon> = {
  Activity,
  AlignCenter,
  AppWindow,
  Award,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeAlert,
  BarChart3,
  Bot, 
  Braces,
  Brain,
  Briefcase,
  Building, 
  CalendarDays,
  CheckSquare,
  ChevronDown,
  Cloud,
  Code,
  CodeXml, 
  Component,
  Cpu,
  Database,
  DollarSign,
  Edit,
  ExternalLink, 
  Eye,
  EyeOff,
  FileQuestion,
  FileText,
  FolderGit2,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  HardDrive,
  HelpCircle,
  Home,
  Info,
  Keyboard,
  KeyRound: Settings, 
  Laptop,
  Layers,
  LayoutGrid,
  Lightbulb,
  LinkIconLucide, 
  Linkedin: Users, 
  Loader2: Activity, 
  LogOut,
  Mail,
  MapPin: Globe, 
  Menu,
  MessageCircleQuestion,
  MessageSquare,
  MessageSquareText,
  MoreHorizontal,
  Network,
  Package,
  Palette,
  PanelLeft,
  PenTool,
  Phone: Smartphone, 
  PlusCircle,
  Puzzle,
  Quote,
  Save,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Star,
  Tablet,
  Tag: Palette, 
  Target,
  Terminal,
  Trash2,
  TrendingUp,
  Twitter: MessageSquare, 
  UserCircle,
  UserIconLucide, 
  Users,
  Webhook,
  Wifi,
  X,
  Zap,
};

// Ensure availableIcons only contains keys that are truly in iconMap
const validIconKeys = Object.keys(iconMap) as Array<keyof typeof iconMap>;
export const availableIcons: ReadonlyArray<string> = [...new Set(validIconKeys)].sort();

export const getIconComponent = (iconName?: string): LucideIcon => {
  if (iconName && iconMap[iconName]) {
    return iconMap[iconName];
  }
  return Code; // Default icon
};
